package common

const (
	OK                   = "OK"
	INVALID_REQUEST      = "INVALID_REQUEST"
	IVALID_JSON_REQUEST  = "IVALID_JSON_REQUEST"
	INVALID_ID_REQUEST   = "IVALID_ID_REQUEST"
	NOT_FOUND            = "NOT_FOUND"
	NOT_FOUND_ID         = "NOT_FOUND_ID"
	FILTER_EMPTY         = "FILTER_EMPTY"
	INVALID_PHONE_NUMBER = "INVALID_PHONE_NUMBER"
	TIME_IS_BUSY         = "TIME_IS_BUSY"
	INVALID_DOCTOR_ID    = "INVALID_DOCTOR_ID"
	INVALID_PATIENT_ID   = "INVALID_PATIENT_ID"
	DAY_IS_OFF           = "DAY_IS_OFF"
	EXPIRED_DATE         = "EXPIRED_DATE"
	TOO_LATE_DATE        = "TOO_LATE_DATE"
	NON_WORKING_HOUR     = "NON_WORKING_HOUR"
)
